name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: cheoberin/pipeline:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  test-job:
      uses: appleboy/discord-action@master
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        payload: |
          {
            "username": "SAST Bot",
            "avatar_url": "https://avatars.githubusercontent.com/u/82663776?s=200&v=4",
            "content": "SonarLint scan complete"
          }

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
